apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
  labels:
    app: new-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-deploy
  template:
    metadata:
      labels:
        app: new-deploy
    spec:
      containers:
      - name: new-deploy
        image: nwajienelson/webapp:${VERSION}
        ports:
        - containerPort: 80
